version: "3.7"
services:
  ################################################################
  # The Zookeeper Cluster - Node-1
  ################################################################  
  zk1:
    image: zookeeper:3.5
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  ################################################################
  # The Zookeeper Cluster - Node-2
  ################################################################        
  zk2:
    image: zookeeper:3.5
    hostname: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
  ################################################################
  # The Zookeeper Cluster - Node-3
  ################################################################        
  zk3:
    image: zookeeper:3.5
    hostname: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
