version: "3.7"
services:
  minio:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=admin12345
    command: server /data
    volumes:
      - /data/minio/data:/data
